name: "Setup R check environment"
description: "Common R environment (Pandoc, system libs, R, renv) for R CMD check and Copilot"

runs:
  using: "composite"
  steps:
    - name: Setup Pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Install system libraries (Linux only)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          libcurl4-openssl-dev \
          libgit2-dev libssh2-1-dev libssl-dev \
          libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev \
          libpng-dev libtiff5-dev libjpeg-dev libcairo2-dev \
          libx11-dev \
          libxml2-dev

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: renv          # pick R version from renv.lock
        Ncpus: 6
        use-public-rspm: true    # faster Linux binaries

    - name: Setup renv
      uses: r-lib/actions/setup-renv@v2
