
# Set
x = setnew(1, 2,    "1", "2")
y = setnew(   2, 3,      "2", "3")
expect_false(x < y)
expect_false(x <= y)
expect_false(x > y)
expect_false(x >= y)
expect_false(y < x)
expect_false(y <= x)
expect_false(y >= x)
expect_true((x + y) > x)
expect_true((x + y) > y)
expect_true((x & y) < x)
expect_true((x - y) < x)
expect_true(x == x)
expect_true(x >= x)
expect_true(x <= x)
expect_true(y == y)
expect_true(y >= y)
expect_true(y <= y)
expect_true(x != y)

x = setnew(1)
y = setnew(1, "1")
expect_true(x != y)

